setup: |
  echo "🐊 Attempt to install exposition engineering tools"
  echo "🐊 Using pipx to perform program installation"
  echo "🐊 Will not re-install if already installed"
  pipx install pymarkdownlnt
---

# Checks on Files {{{

# perform checks on a file
- writing/characterization/podcast_visual_identity.md:
    - description: Ensure that the podcast_visual_identity.md file exists in the writing/characterization/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for the reflection
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Delete the 'Add Your Name Here' prompt in the reflection file
      check: MatchFileFragment
      options:
        fragment: "Add Your Name Here"
        count: 0
        exact: true
    - description: Retype the every word in the Honor Code pledge in reflection.md
      check: MatchFileFragment
      options:
        fragment: "I adhered to the Allegheny College Honor Code while completing this project."
        count: 3
        exact: true
    - description: Confirm that the markdown file containing the visual identity has the correct number of headers
      check: CountMarkdownTags
      options:
        tag: heading
        count: 14
        exact: true
    - description: Confirm that the markdown file containing the visual identity has the correct number of lists
      check: CountMarkdownTags
      options:
        tag: list
        count: 6
        exact: true
    - description: Confirm that the markdown file containing the visual identity has the correct number of links
      check: CountMarkdownTags
      options:
        tag: link
        count: 18
        exact: false
    - description: Confirm that the markdown file containing the visual identity has the HTML block markers
      check: CountMarkdownTags
      options:
        tag: html_block
        count: 2
        exact: false
    - description: Confirm that the markdown file containing the visual identity has a visual detail of colors
      check: MatchFileFragment
      options:
        fragment: "**Colors**:"
        count: 1
        exact: true
    - description: Confirm that the markdown file containing the visual identity has a visual detail 
      check: MatchFileFragment
      options:
        fragment: "**Fonts**"
        count: 1
        exact: true
    - description: Confirm that the markdown file containing the visual identity has a visual detail of styles
      check: MatchFileFragment
      options:
        fragment: "**Styles**"
        count: 1
        exact: true
    - description: Confirm that the markdown file containing the visual identity has a label for a Canva link
      check: MatchFileFragment
      options:
        fragment: "**Link to the Canva Logo on Canva Web Site**"
        count: 1
        exact: true
    - description: Confirm that the markdown file containing the visual identity has a label for a GitHub repo
      check: MatchFileFragment
      options:
        fragment: "**Link to the Canva Logo in Your GitHub Repository**"
        count: 1
        exact: true

# perform checks on a file
- image/podcast_logo.png:
    - description: Ensure that the podcast logo file with the png filename extension exists in the image/ directory
      check: ConfirmFileExists

# }}}

# Check Output from Linters {{{

# run a check
- description: Confirm that the show characterization file passes the linting checks run by pymarkdownlnt
  command: "pymarkdown --config .pymarkdown.cfg scan writing/characterization/podcast_visual_identity.md"

# }}}

# Commits {{{

# count number of commits in the GitHub repository
- description: Have at least a specific minimum of commits in repository
  check: CountCommits
  options:
    count: 10

# }}}
